version: '3.8'

services:
  product-service:
    build: ./product-service
    container_name: product
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - msa-network

  order-service:
    build: ./order-service
    container_name: order
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - msa-network

  payment-service:
    build: ./payment-service
    container_name: payment
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - msa-network

networks:
  msa-network:
    driver: bridge

